Vagrant.configure("2") do |config|
  config.vm.define "web" do |master|
    master.vm.box = "centos_docker.box"
    master.vm.hostname = 'master'
    master.vm.network :private_network, ip: "192.168.56.101"

    master.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "master"]
    end
  end

  config.vm.define "node01" do |node01|
    node01.vm.box = "centos_docker.box"
    node01.vm.hostname = 'node01'

    node01.vm.network :private_network, ip: "192.168.56.102"

    node01.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "node01"]
    end
  end

  config.vm.define "node02" do |node02|
    node02.vm.box = "centos_docker.box"
    node02.vm.hostname = 'node02'

    node02.vm.network :private_network, ip: "192.168.56.103"

    node02.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "node02"]
    end
  end

end